### ISSUE TITLE
The image referenced in the documentation lacks required utils (lsblk)

### ISSUE THREAD

**Issue by javierpena** [red-hat-storage/lvm-operator#106]
When trying to deploy the operator using the prebuilt image referenced in the documentation (quay.io/mulbc/lvm-operator), everything seems to work fine until you create the LVMCluster resource. All pods are started, but when creating a pvc and a pod, nothing happens.

Looking at the pod logs, I found the following in the vg-manager pod:

{"level":"error","ts":1644504805.3839536,"logger":"controller.lvmvolumegroup","msg":"Reconciler error","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vglvmoperator","namespace":"lvm-operator-system","error":"failed to list block devices: exec: \"lsblk\": executable file not found in $PATH","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:227"}

It looks like the image is based on Fedora 35, and lacks the util-linux package that provides lsblk.

I managed to build the images manually (replacing centos:8 with centos:stream8 in the Dockerfile definition), and then everything worked as expected.

**Comment by nbalacha** [comment]
Thanks for reporting this.The image has been updated and should work now.
