### ISSUE TITLE
vg-manager failed to create/extend volume group.

### ISSUE THREAD

**Issue by ianmaclean23** [red-hat-storage/lvm-operator#191]
Using prebuilt lvm image.

sh-4.4# lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0   250G  0 disk 
|-sda1   8:1    0     1M  0 part 
|-sda2   8:2    0   127M  0 part 
|-sda3   8:3    0   384M  0 part 
`-sda4   8:4    0 249.5G  0 part /dev/termination-log
sdb      8:16   0   250G  0 disk 
sr0     11:0    1  1024M  0 rom 

Pod log:
{"level":"info","ts":1652381771.6423192,"logger":"controller.lvmvolumegroup.vg-manager","msg":"reconciling","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","lvmvolumegroup":"lvm-operator-system/vg1"}
{"level":"info","ts":1652381771.6431682,"logger":"controller.lvmvolumegroup.vg-manager","msg":"getting block devices for volumegroup","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","VGName":"vg1"}
{"level":"info","ts":1652381771.6524365,"logger":"controller.lvmvolumegroup.vg-manager","msg":"does not match filter","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","Device.Name":"sda","filter.Name":"noChildren"}
{"level":"info","ts":1652381771.6624043,"logger":"controller.lvmvolumegroup.vg-manager","msg":"does not match filter","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","Device.Name":"sr0","filter.Name":"usableDeviceType"}
{"level":"info","ts":1652381771.6625292,"logger":"controller.lvmvolumegroup.vg-manager","msg":"lvmd config file doesn't exist, will create","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system"}
{"level":"info","ts":1652381771.7175312,"logger":"controller.lvmvolumegroup.vg-manager","msg":"creating a new volume group","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","VGName":"vg1"}
{"level":"error","ts":1652381771.7751362,"logger":"controller.lvmvolumegroup.vg-manager","msg":"failed to create/extend volume group","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","VGName":"vg1","error":"failed to create or extend volume group \"vg1\". exit status 5","stacktrace":"github.com/red-hat-storage/lvm-operator/pkg/vgmanager.(*VGReconciler).Reconcile\n\t/workspace/pkg/vgmanager/vgmanager_controller.go:97\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227"}

oc describe pod vg-manager-9zjnk
Name:         vg-manager-9zjnk
Namespace:    lvm-operator-system
Priority:     0
Node:         mx-sno-ocp/192.168.5.89
Start Time:   Thu, 12 May 2022 18:53:41 +0000
Labels:       app.lvm.openshift.io=vg-manager
              controller-revision-hash=749865ff7b
              pod-template-generation=1
Annotations:  k8s.ovn.org/pod-networks:
                {"default":{"ip_addresses":["10.128.1.3/23"],"mac_address":"0a:58:0a:80:01:03","gateway_ips":["10.128.0.1"],"ip_address":"10.128.1.3/23","...
              k8s.v1.cni.cncf.io/network-status:
                [{
                    "name": "ovn-kubernetes",
                    "interface": "eth0",
                    "ips": [
                        "10.128.1.3"
                    ],
                    "mac": "0a:58:0a:80:01:03",
                    "default": true,
                    "dns": {}
                }]
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "ovn-kubernetes",
                    "interface": "eth0",
                    "ips": [
                        "10.128.1.3"
                    ],
                    "mac": "0a:58:0a:80:01:03",
                    "default": true,
                    "dns": {}
                }]
              openshift.io/scc: odf-lvm-vgmanager
Status:       Running
IP:           10.128.1.3
IPs:
  IP:           10.128.1.3
Controlled By:  DaemonSet/vg-manager
Containers:
  vg-manager:
    Container ID:  cri-o://48330dd0356d83e383da84159ffd544c1a17b68f3bf778ace9f407e43a76947a
    Image:         quay.io/ocs-dev/lvm-operator:latest
    Image ID:      quay.io/ocs-dev/lvm-operator@sha256:642717a0be4c9fbb5be6b3c9891bcaa16634dadacb7a269996722af0bb8e7fb6
    Port:          <none>
    Host Port:     <none>
    Command:
      /vgmanager
    State:          Running
      Started:      Thu, 12 May 2022 18:53:43 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      NODE_NAME:       (v1:spec.nodeName)
      POD_NAMESPACE:  lvm-operator-system (v1:metadata.namespace)
      POD_NAME:       vg-manager-9zjnk (v1:metadata.name)
    Mounts:
      /dev from device-dir (rw)
      /etc/topolvm from lvmd-conf (rw)
      /run/udev from run-udev (rw)
      /sys from sys (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-qt64z (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  lvmd-conf:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/topolvm
    HostPathType:  DirectoryOrCreate
  device-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  Directory
  run-udev:
    Type:          HostPath (bare host directory volume)
    Path:          /run/udev
    HostPathType:  
  sys:
    Type:          HostPath (bare host directory volume)
    Path:          /sys
    HostPathType:  
  kube-api-access-qt64z:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
    ConfigMapName:           openshift-service-ca.crt
    ConfigMapOptional:       <nil>
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type    Reason          Age    From               Message
  ----    ------          ----   ----               -------
  Normal  Scheduled       7m11s  default-scheduler  Successfully assigned lvm-operator-system/vg-manager-9zjnk to mx-sno-ocp
  Normal  AddedInterface  7m9s   multus             Add eth0 [10.128.1.3/23] from ovn-kubernetes
  Normal  Pulling         7m9s   kubelet            Pulling image "quay.io/ocs-dev/lvm-operator:latest"
  Normal  Pulled          7m9s   kubelet            Successfully pulled image "quay.io/ocs-dev/lvm-operator:latest" in 478.429234ms
  Normal  Created         7m9s   kubelet            Created container vg-manager
  Normal  Started         7m9s   kubelet            Started container vg-manager

**Comment by sp98** [comment]
Looks like its failing to create volume group using the disk `sdb`
`"error":"failed to create or extend volume group "vg1". exit status 5"` is not very helpful error message to debug further. We need to add `verbose` error to the logs. 

@ianmaclean23  Is it possible for you to manually create the volume group on disk `sdb` and share the results. 

You can use the below command : 

`vgcreate vg1 /dev/sdb -v`

**Comment by ianmaclean23** [comment]
Thank you.
I had a partition on this that I had deleted previously, guess there was a reference to it left somewhere.
Running the command asked me to delete it, deleting it allowed it to be created successfully.
