### ISSUE TITLE
Config file is not created by the LVM operator.           

### ISSUE THREAD

**Issue by sbudhira** [red-hat-storage/lvm-operator#207]
I am getting "waiting for lvmd config file" in the topolvm-node pod's log for the file checker container. 

sh-4.4# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sr0          11:0    1  1024M  0 rom  
nvme0n1     259:0    0  1000G  0 disk 
|-nvme0n1p1 259:1    0     1M  0 part 
|-nvme0n1p2 259:2    0   127M  0 part 
|-nvme0n1p3 259:3    0   384M  0 part 
`-nvme0n1p4 259:4    0 999.5G  0 part /dev/termination-log

**Comment by nbalacha** [comment]
lvmo currently requires whole , unpartitioned disks. It looks like there is currently no disk it can use on the system.

**Comment by sbudhira** [comment]
Added 2nd disk still not able to create the config file.
sh-4.4# lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sr0          11:0    1  1024M  0 rom  
nvme0n1     259:0    0  1000G  0 disk 
|-nvme0n1p1 259:1    0     1M  0 part 
|-nvme0n1p2 259:2    0   127M  0 part 
|-nvme0n1p3 259:3    0   384M  0 part 
`-nvme0n1p4 259:4    0 999.5G  0 part /dev/termination-log
**nvme0n2     259:5    0   200G  0 disk** 


error:
`{"level":"info","ts":1655245136.9076426,"logger":"controller.lvmvolumegroup.vg-manager","msg":"does not match filter","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","Device.Name":"nvme0n2","filter.Name":"noFilesystemSignature"}`

How to fix the above error?.
-----------------

`{"level":"info","ts":1655245136.8795693,"logger":"controller.lvmvolumegroup.vg-manager","msg":"getting block devices for volumegroup","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","VGName":"vg1"}
{"level":"info","ts":1655245136.8948176,"logger":"controller.lvmvolumegroup.vg-manager","msg":"does not match filter","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","Device.Name":"sr0","filter.Name":"usableDeviceType"}
{"level":"info","ts":1655245136.907544,"logger":"controller.lvmvolumegroup.vg-manager","msg":"does not match filter","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","Device.Name":"nvme0n1","filter.Name":"noChildren"}
{"level":"info","ts":1655245136.9076426,"logger":"controller.lvmvolumegroup.vg-manager","msg":"does not match filter","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","Device.Name":"nvme0n2","filter.Name":"noFilesystemSignature"}
{"level":"info","ts":1655245136.9077005,"logger":"controller.lvmvolumegroup.vg-manager","msg":"lvmd config file doesn't exist, will create","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system"}
{"level":"info","ts":1655245136.90775,"logger":"controller.lvmvolumegroup.vg-manager","msg":"no matching devices for volume group","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","VGName":"vg1"}
{"level":"info","ts":1655245136.907787,"logger":"controller.lvmvolumegroup.vg-manager","msg":"reconcile complete","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","result":{"Requeue":false,"RequeueAfter":0}}`

error:
`{"level":"info","ts":1655245136.9076426,"logger":"controller.lvmvolumegroup.vg-manager","msg":"does not match filter","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","Device.Name":"nvme0n2","filter.Name":"noFilesystemSignature"}`

**Comment by nbalacha** [comment]
`{"level":"info","ts":1655245136.9076426,"logger":"controller.lvmvolumegroup.vg-manager","msg":"does not match filter","reconciler group":"lvm.topolvm.io","reconciler kind":"LVMVolumeGroup","name":"vg1","namespace":"lvm-operator-system","Device.Name":"nvme0n2","filter.Name":"noFilesystemSignature"}`

Please check if there is a filesystem on the device. If yes, please wipe the disk and try again.

**Comment by nbalacha** [comment]
Hi @sbudhira . Did this work?

**Comment by karmab** [comment]
this happens in our env although vgs and pvs get created fine

```
sh-4.4# vgs
  VG  #PV #LV #SN Attr   VSize  VFree
  vg1   3   5   0 wz--n- <3.93t <3.14t
sh-4.4# pvs
  PV           VG  Fmt  Attr PSize    PFree
  /dev/nvme0n1 vg1 lvm2 a--    <1.75t  978.49g
  /dev/nvme1n1 vg1 lvm2 a--    <1.75t   <1.75t
  /dev/nvme3n1 vg1 lvm2 a--  <447.13g <447.13g
```

**Comment by nbalacha** [comment]
Hi @sbudhira . I am closing this issue. Please reopen it if you are still seeing the problem.
