### ISSUE TITLE
LVMVolumeGroupNodeStatus CR name should follow DNS naming standard.

### ISSUE THREAD

**Issue by sp98** [red-hat-storage/lvm-operator#77]
`LVMVolumeGroupNodeStatus` CR [name](https://github.com/red-hat-storage/lvm-operator/blob/a5ee8b9d87b19b0cb18dd555bcf923dde6d3a5d5/pkg/vgmanager/vgmanager_controller.go#L332) uses the `node` name directly. This might not always follow the DNS naming standards for K8s resources.

**Comment by travisn** [comment]
Can you expand on the concern for using the node name as the CR name? A couple thoughts:
- The proper dns host name is found on a node with the label `kubernetes.io/hostname`, which is also mutable. It seems like a good thing to use the immutable node name as the CR name. 
- Any node name should also be compatible with a CR name.

**Comment by sp98** [comment]
@travisn  You are right.  Node name can be used as CR name. I was thinking about the `truncate node name` method used in rook where we truncate the node name if its greater than certain chars.   Closing this issue.
