### ISSUE TITLE
Deployment fails due to dockerhub pull rate limit

### ISSUE THREAD

**Issue by mulbc** [red-hat-storage/lvm-operator#88]
The LVMCluster creation is stuck in a loop, because the topolvm-controller waits for its initContainer, which wants to pull "alpine/openssl".
It fails to pull this container from Dockerhub (the only location where this is available) due to DockerHubs pull rate limite:

```
Failed to pull image "alpine/openssl": rpc error: code = Unknown desc = initializing source docker://alpine/openssl:latest: reading manifest latest in docker.io/alpine/openssl: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

Can we use a different image? As a quick workaround, I rehosted the image at `quay.io/mulbc/alpine-openssl`

**Comment by leelavg** [comment]
@mulbc 
- thanks for raising the issue
- this is a know issue and more than often kubelet is able to pull the image eventually 
- however, not depending on that, already made changes #94 to use same operator image for all supporting containers

**Comment by nbalacha** [comment]
Closing this issue as the fix has been merged.
